### ISSUE TITLE
如何添加背景图

### ISSUE THREAD

**Issue by summerking1** [taixingyiji/blog#1]
您好，访问您的博客时，看到了背景图很nice,想询问下如何设置呢？
顺便可以交换下友链么？❤
- name: 小夏的博客 # 昵称
  desc: Devops运维技术博客 # 介绍
  avatar: https://cdn.jsdelivr.net/gh/summerking1/image@main/tx.png # 头像
  link: https://www.xswsym.online/

**Comment by taixingyiji** [comment]
> 您好，访问您的博客时，看到了背景图很nice,想询问下如何设置呢？
> 顺便可以交换下友链么？❤
> 
> * name: 小夏的博客 # 昵称
>   desc: Devops运维技术博客 # 介绍
>   avatar: https://cdn.jsdelivr.net/gh/summerking1/image@main/tx.png # 头像
>   link: https://www.xswsym.online/

![image](https://user-images.githubusercontent.com/51304768/104696391-2cc0e400-5749-11eb-91cb-d0e6cf7258fd.png)

已经添加友链~

- name: Lake's blog # 昵称
  desc: 不积跬步，无以至千里；不积小流，无以成江海。 # 介绍
  avatar: https://cdn.jsdelivr.net/gh/taixingyiji/image_store@main/blog/logo/img.png # 头像
  link: https://taixingyiji.com/  # 链接
